---
# tasks file for rsyslog (Debian)

- name: Install rsyslog packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ rsyslog_packages }}"
  tags:
    - rsyslog

- name: Create rsyslog ufw configuration file
  become: yes
  template:
    src: 20-ufw.conf.j2
    dest: /etc/rsyslog.d/20-ufw.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  tags:
    - rsyslog
