---
# tasks file for rsyslog (CentOS specific)
- name: Add Rsyslog Repository
  yum_repository:
    name: rsyslog_v8
    description: Adiscon CentOS Rsyslog
    baseurl: http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch
    gpgkey: http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
    gpgcheck: yes

- name: Install rsyslog packages
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ rsyslog_packages }}"
  tags:
    - rsyslog
