# Dockerfile.debian
FROM debian:jessie-slim

# Install Ansible
RUN apt-get update && apt-get install -y software-properties-common git
RUN
RUN apt-get update
#RUN apt-get install -y ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
