# Dockerfile.debian
FROM debian:8.7

# Install Ansible
RUN apt-get update && apt-get install -y software-properties-common git-core
RUN apt-get install -y ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
